package_assets:          on
embed_assets:            off    # on, off, datauri
compress_assets:         on
gzip_assets:             on
javascript_compressor:   yui

javascripts: 
  base: 
    - 'src/javascripts/jquery-1.5.1.min.js'
    - 'src/javascripts/jquery-ui-1.8.11.custom.js'
    - 'src/javascripts/jquery.ui.selectmenu.js'
    - 'src/javascripts/jquery.placeholder.js'
    - 'src/javascripts/application.js'
